services:
  auth:
    build: ./apps/auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "5238:5238"
    volumes:
      - ./apps/auth:/app
      - /app/obj
      - /app/bin  
    depends_on:
      - db
      
  game:
    build: 
      context: .
      dockerfile: ./apps/game/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev
      - ASPNETCORE_URLS=http://+:8000
    ports: 
      - "80:8000"
    volumes:
      - .:/workspace  
      - /workspace/apps/game/obj
      - /workspace/apps/game/bin
    working_dir: /workspace/apps/game
    depends_on:
      - db
    
    # Working_dir define the dir where commands will be execute
    # Remove bin / obj from the working dir to avoid potential errors
      
  db: 
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: vortexdb
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    
  adminer: 
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mariadb_data: