services:
  auth:
    build: ./apps/auth
    ports:
      - "5238:5238"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    volumes:
      - ./apps/auth:/app
      - /app/obj
      - /app/bin  
    depends_on:
      - db
      
  game:
    build: ./apps/game
    ports: 
      - "80:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev
      - ASPNETCORE_URLS=http://+:8000
    depends_on:
      - db
      
  db: 
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: vortexdb
    ports:
      - "3307:3306"
    
  adminer: 
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db