version: "3.9"

services:
  auth:
    build: ./auth
    ports: 
      - "5005:5238"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev
      - ASPNETCORE_URLS=http://+:5238
    depends_on:
      - db
      
  game:
    build: ./game
    ports: 
      - "80:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Dev
      - ASPNETCORE_URLS=http://+:8000
    depends_on:
      - db
      
  db: 
    image: mariadb
    restart: always
    ports:
      - "3307:3306"  # Changement ici : port externe 3307
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: vortexdb
    
  adminer: 
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
